name: Build Optimized Executables

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'
  APP_NAME: '24fire'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            artifact_name: 24fire.exe
            asset_name: 24fire-windows.exe
          - os: ubuntu-latest
            artifact_name: 24fire
            asset_name: 24fire-linux
          - os: macos-latest
            artifact_name: 24fire
            asset_name: 24fire-macos
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build executable (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        pyinstaller --onefile --name=${{ env.APP_NAME }} --console --add-data ".env;." --hidden-import=dotenv --hidden-import=requests --optimize=2 main.py
        
    - name: Build executable (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        pyinstaller --onefile --name=${{ env.APP_NAME }} --console --add-data ".env:." --hidden-import=dotenv --hidden-import=requests --optimize=2 main.py
        
    - name: Test executable (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        dist\${{ env.APP_NAME }}.exe --help
        
    - name: Test executable (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        chmod +x dist/${{ env.APP_NAME }}
        ./dist/${{ env.APP_NAME }} --help
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@4.6.2
      with:
        name: ${{ matrix.asset_name }}
        path: dist/${{ matrix.artifact_name }}
        retention-days: 30
        
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/${{ matrix.artifact_name }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}