name: Build Windows Executable

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --name=24fire --icon=icon.ico --add-data ".env;." --hidden-import=dotenv main.py
        
    - name: Test executable
      run: |
        dist\24fire.exe --help
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: 24fire-windows
        path: dist/24fire.exe
        
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/24fire.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --name=24fire --add-data ".env:." --hidden-import=dotenv main.py
        
    - name: Test executable
      run: |
        ./dist/24fire --help
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: 24fire-linux
        path: dist/24fire
        
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/24fire
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --name=24fire --add-data ".env:." --hidden-import=dotenv main.py
        
    - name: Test executable
      run: |
        ./dist/24fire --help
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: 24fire-macos
        path: dist/24fire
        
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/24fire
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}